//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGRules.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTGRules.Resources.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string aboutButton {
            get {
                return ResourceManager.GetString("aboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyway, thanks for using the App!.
        /// </summary>
        public static string anywayThanksForUsingApp {
            get {
                return ResourceManager.GetString("anywayThanksForUsingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change rules.
        /// </summary>
        public static string changeRulesButton {
            get {
                return ResourceManager.GetString("changeRulesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        public static string changeThemeButton {
            get {
                return ResourceManager.GetString("changeThemeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cache.
        /// </summary>
        public static string clearCacheButton {
            get {
                return ResourceManager.GetString("clearCacheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGED TO.
        /// </summary>
        public static string compareChangedTo {
            get {
                return ResourceManager.GetString("compareChangedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare rules (experimental).
        /// </summary>
        public static string compareRulesButton {
            get {
                return ResourceManager.GetString("compareRulesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string copyToClipboard {
            get {
                return ResourceManager.GetString("copyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string donateButton {
            get {
                return ResourceManager.GetString("donateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading last rules.
        /// </summary>
        public static string errorLoadingLastRules {
            get {
                return ResourceManager.GetString("errorLoadingLastRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading rules.
        /// </summary>
        public static string errorLoadingRules {
            get {
                return ResourceManager.GetString("errorLoadingRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred.
        /// </summary>
        public static string errorOcurred {
            get {
                return ResourceManager.GetString("errorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred (Last donation pending or server error).
        /// </summary>
        public static string errorOcurredDonationPendingOrServerError {
            get {
                return ResourceManager.GetString("errorOcurredDonationPendingOrServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string homeButton {
            get {
                return ResourceManager.GetString("homeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string newest {
            get {
                return ResourceManager.GetString("newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not active donations. Thanks for trying!.
        /// </summary>
        public static string noActiveDonations {
            get {
                return ResourceManager.GetString("noActiveDonations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random rule.
        /// </summary>
        public static string randomRuleButton {
            get {
                return ResourceManager.GetString("randomRuleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read text.
        /// </summary>
        public static string readText {
            get {
                return ResourceManager.GetString("readText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart to apply the changes.
        /// </summary>
        public static string restartToApply {
            get {
                return ResourceManager.GetString("restartToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string searchButton {
            get {
                return ResourceManager.GetString("searchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term must have at least 3 characters.
        /// </summary>
        public static string searchTerm3Characters {
            get {
                return ResourceManager.GetString("searchTerm3Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term.
        /// </summary>
        public static string searchTextBox {
            get {
                return ResourceManager.GetString("searchTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the new rules.
        /// </summary>
        public static string selectNewRules {
            get {
                return ResourceManager.GetString("selectNewRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the old rules.
        /// </summary>
        public static string selectOldRules {
            get {
                return ResourceManager.GetString("selectOldRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the rules.
        /// </summary>
        public static string selectTheRules {
            get {
                return ResourceManager.GetString("selectTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks anyway. If you want, try again later, or rate the App in the store :).
        /// </summary>
        public static string thanksAnywayTryAgainOrRate {
            get {
                return ResourceManager.GetString("thanksAnywayTryAgainOrRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for the donation!.
        /// </summary>
        public static string thanksForDonation {
            get {
                return ResourceManager.GetString("thanksForDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use dark theme.
        /// </summary>
        public static string useDarkTheme {
            get {
                return ResourceManager.GetString("useDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use light theme.
        /// </summary>
        public static string useLightTheme {
            get {
                return ResourceManager.GetString("useLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using rules:.
        /// </summary>
        public static string usingRulesText {
            get {
                return ResourceManager.GetString("usingRulesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want, rate the App in the store :).
        /// </summary>
        public static string youCanRate {
            get {
                return ResourceManager.GetString("youCanRate", resourceCulture);
            }
        }
    }
}
